#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

source $CABAL_ROOT/callers/includes.sh

function say_marco() {
	if [ $(uname) = "Darwin" ]; then
		say "marco"
	else
		echo "marco" | festival --tts
	fi
}

say_marco && cabal_query marco x
