#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

CABAL_ROOT="$(git rev-parse --show-toplevel)"

source $CABAL_ROOT/callers/includes.sh

function say_marco() {
	if [ $(uname) = "Darwin" ]; then
		say "marco"
	else
		#echo "marco" | festival --tts
		espeak-ng "marco"
	fi
}

say_marco && cabal_query marco x
