#!/bin/bash

source "$(git rev-parse --show-toplevel)/vars.sh"

serf agent \
	-config-dir=$CABAL_ROOT/config.d \
	-keyring-file=$CABAL_ROOT/key/ring.json \
	-bind=0.0.0.0:$CABAL_PORT \
	-log-level=$CABAL_LOG_LEVEL
