CABAL_NAMESPACE="ca.fukt.cabal"
CABAL_ROOT="$HOME/.config/cabal"
CABAL_BIN_ROOT="$HOME/.local/bin"
CABAL_VERSION=v0.0.2
CABAL_PORT=9095
CABAL_CLUSTER=zoo
CABAL_LOG_LEVEL=info

export CABAL_NAMESPACE
export CABAL_ROOT
export CABAL_BIN_ROOT
export CABAL_VERSION
export CABAL_PORT
export CABAL_CLUSTER
export CABAL_LOG_LEVEL
